## Loading data

In [90]:
import pandas as pd

columns_meaning = pd.read_excel(
    '../data/Base_open_data_BMO_2025.xlsx',
    usecols="B:C",
    skiprows=6,
    nrows=15
)
df = pd.read_excel('../data/Base_open_data_BMO_2025.xlsx', sheet_name="BMO_2025_open_data")

In [91]:
print(columns_meaning)

         Variables                                        Description
0             annee                                               2025
1   Code métier BMO                              Code métier BMO (FAP)
2    Nom métier BMO                                libellé métier BMO
3       Famille_met                             Code famille de métier
4       Lbl_fam_met                          libellé famille de métier
5               REG                                  Code région Insee
6           NOM_REG                                  Nom de la région
7              Dept                                 N° de département
8           NomDept                                Nom du département
9              BE25                              Code bassin d'emploi
10          NOMBE25                             Nom du bassin d'emploi
11              met                   Nombre de projet de recrutement
12             xmet  Nombre de projets de recrutement jugés difficiles
13             smet       Nombre de projets de recrutement saisonniers

In [92]:
df.head()

,annee,Code métier BMO,Nom métier BMO,Famille_met,Lbl_fam_met,REG,NOM_REG,Dept,NomDept,BE25,NOMBE25,met,xmet,smet
0,2025,A0X40,Agriculteurs,Z,Autres métiers,1,Guadeloupe,971,Guadeloupe,101,BASSIN BASSE-TERRE,227,80,128
1,2025,A0X40,Agriculteurs,Z,Autres métiers,1,Guadeloupe,971,Guadeloupe,102,BASSIN GRANDE-TERRE,91,42,82
2,2025,A0X40,Agriculteurs,Z,Autres métiers,1,Guadeloupe,971,Guadeloupe,105,BASSIN CENTRE,57,52,7
3,2025,A0X40,Agriculteurs,Z,Autres métiers,1,Guadeloupe,971,Guadeloupe,113,BASSIN ILES DU NORD,26,*,26
4,2025,A0X40,Agriculteurs,Z,Autres métiers,1,Guadeloupe,971,Guadeloupe,116,BASSIN MARIE-GALANTE,*,*,*

## Cleaning data

In [93]:
cols_to_convert = ["met", "xmet", "smet"]
df[cols_to_convert] = df[cols_to_convert].replace('*', 0).apply(pd.to_numeric)

## Exploring jobs

In [94]:
df_jobs = df[['Nom métier BMO', 'Lbl_fam_met']]
df_unique = df_jobs.drop_duplicates(subset='Nom métier BMO')
df_sorted = df_unique.sort_values(by='Lbl_fam_met')
grouped = df_sorted.groupby('Lbl_fam_met')

In [95]:
for fam, group in grouped:
    print(f"\n=== {fam} ===")
    for job in group['Nom métier BMO']:
        print(f"- {job}")

=== Autres métiers ===
- Agriculteurs
- Magasiniers et préparateurs de commandes peu qualifiés
- Conducteurs d’engins légers de déplacement de charges, cariste
- Manutentionnaires et déménageurs qualifiés
- Manutentionnaires et déménageurs peu qualifiés
- Facteurs et distributeurs de documents (non cadres)
- Conducteurs de véhicules légers
- Conducteurs de transport en commun sur route
- Conducteurs et livreurs sur courte distance (hors distribution de documents)
- Conducteurs routiers
- Conducteurs sur rails et d'engins de traction
- Magasiniers et préparateurs de commande qualifiés
- Responsable du magasinage et de la logistique (non cadres)
- Cadres et maîtres d'équipage de la marine
- Eleveurs
- Bûcherons, sylviculteurs et agents forestiers
- Conducteurs d'engins agricoles ou forestiers
- Maraîchers et horticulteurs
- Jardiniers des espaces verts et naturels
- Viticulteurs, arboriculteurs
- Techniciens et agents d'encadrement d'exploitations agricoles
- Marins
- Pêcheurs et aquaculteurs
- Ingénieurs, cadres techniques de l'agriculture

=== Autres techniciens et employés ===
- Techniciens et agents de maîtrise en installation et maintenance en froid et conditionnement d'air
- Techniciens et agents de maîtrise en maintenance de véhicules
- Techniciens et agents de maîtrise en maintenance générale et mécanique industrielle
- Agents de maitrise et assimilés des industries de process
- Conducteurs de travaux et chefs de chantier non cadres
- Techniciens d'étude, recherche et développement
- Techniciens, agents de maîtrise et assimilés en électricité et en électronique
- Techniciens et agents de maîtrise en assistance et support technique client et en installation et maintenance télécoms et courants faibles
- Dessinateurs en bâtiment et en travaux publics
- Techniciens experts et chargés d’études du BTP
- Géomètres
- Ingénieurs et cadres de fabrication et de la production
- Techniciens et agents de maîtrise en maintenance électrique, électronique et automatismes
- Techniciens et agents de maîtrise de la logistique, du planning, de l'ordonnancement et méthodes en industrialisation
- Techniciens du contrôle qualité
- Techniciens du dessin industriel
- Agents de maîtrise et assimilés en fabrication mécanique

=== Fonctions administratives ===
- Techniciens des services administratifs
- Secrétaires de direction
- Agents administratifs
- Secrétaires bureautiques et assimilés
- Employés de la comptabilité
- Techniciens de production, d'exploitation, d'installation, et de maintenance, support et services aux utilisateurs en informatique
- Techniciens d'étude et de développement en informatique
- Agents d'accueil et d'information
- Techniciens et agents de maîtrise des services financiers ou comptables

=== Fonctions d'encadrement ===
- Cadres administratifs, comptables et financiers (hors juristes)
- Professeurs du secondaire
- Cadres de la logistique
- Personnels techniques navigants de l’aviation
- Professeurs du supérieur
- Juristes et avocats
- Techniciens et agents de maîtrise chargés d'études socio-économiques
- Cadres des ressources humaines et du recrutement
- Ingénieurs et cadres d'étude, recherche et développement en informatique et télécom
- Dirigeants de petites et moyennes entreprises de moins de 50 salariés
- Cadres de la communication
- Cadres et techniciens de la documentation
- Journalistes et cadres de l'édition
- Professionnels des spectacles
- Photographes
- Graphistes, dessinateurs, stylistes, décorateurs et créateurs de supports de communication visuelle
- Interprètes
- Artistes (musique, danse, spectacles)
- Artistes plasticiens
- Médecins
- Dentistes
- Vétérinaires
- Pharmaciens
- Professeurs des écoles
- Écrivains
- Assistants de la communication
- Patrons et cadres de l’hôtellerie et de la restauration
- Cadres agents immobiliers et syndics
- Cadres dirigeants des grandes entreprises de plus de 50 salariés
- Directeurs d’établissements du secondaire ou du supérieur et inspecteurs
- Chefs de projet et directeurs de service informatique
- Responsables et cadres de la production, de l'exploitation et de la maintenance informatique et télécom
- Experts et consultants en systèmes d'information
- Chercheurs (sauf industrie et enseignement supérieur)
- Professionnels du droit
- Experts de l'assurance
- Cadres et indépendants commerciaux de la banque
- Managers en banque assurance
- Professions intermédiaires du marketing et des services commerciaux (hors achats)
- Employés et professions intermédiaires de l'immobilier
- Cadres commerciaux, acheteurs et cadres de la mercatique
- Technico-commerciaux
- Cadres du management des magasins
- Chargés d'études socio-économiques
- Ingénieurs et cadres d'étude, recherche et développement (industrie)
- Cadres des transports et du tourisme
- Ingénieurs en maintenance et support technique client
- Ingénieurs et cadres techniques en Hygiène Sécurité Environnement -HSE- industriels et exploitation éco-industriel
- Cadres des études BTP, des études géologiques, du métré de la construction et du contrôle et diagnostic technique du BTP
- Techniciens et agents de maîtrise en distribution et assainissement d'eau et gestion des déchets
- Ingénieurs du bâtiment et des travaux publics, chefs de chantier et conducteurs de travaux (cadres)
- Ingénieurs des méthodes de production, du contrôle qualité
- Architectes
- Techniciens et agents de maîtrise en intervention technique en Hygiène Sécurité Environnement -HSE industriel et protection du patrimoine naturel

=== Fonctions liées à la vente, au tourisme et aux services ===
- Maîtrise des magasins
- Représentants auprès des particuliers
- Attachés commerciaux
- Télévendeurs et téléconseillers
- Bouchers
- Vendeurs en habillement et accessoires, articles de luxe, de sport, de loisirs et culturels
- Vendeurs en ameublement, équipement du foyer, bricolage
- Vendeurs en produits alimentaires
- Caissiers
- Employés de libre service
- Cadres et indépendants commerciaux des assurances
- Employés et techniciens commerciaux des assurances
- Employés des services commerciaux
- Charcutiers, traiteurs
- Cuisiniers
- Aides de cuisine et employés polyvalents de la restauration
- Employés des services divers
- Ouvriers de l'assainissement et du traitement des déchets
- Agents de service hospitaliers
- Agents d'entretien de locaux
- Agents de sécurité et de surveillance
- Concierges
- Assistants maternels, auxiliaires de puériculture, assistants familiaux et gardes à domicile
- Boulangers, pâtissiers
- Aides à domicile et auxiliaires de vie
- Coiffeurs, esthéticiens
- Agents de maîtrise de l'hôtellerie et de la gestion des structures de loisirs
- Agents de maîtrise de la restauration
- Serveurs de cafés restaurants
- Employés de l'hôtellerie
- Chefs cuisiniers
- Employés et techniciens commerciaux de la banque
- Personnels de ménage chez des particuliers
- Gestionnaires de la banque et de l'assurance
- Professions intermédiaires commerciales des achats
- Contrôleurs des transports
- Experts de la banque
- Agents d'exploitation du transport
- Employés du tourisme et agent de billetterie des transports
- Employés administratifs et commerciaux des transports
- Agents et hôtesses d'accompagnement
- Techniciens d'exploitation et d'administration des transports
- Techniciens et agents de maîtrise du tourisme
- Experts de la finance

=== Fonctions sociales et médico-sociales ===
- Professionnels de l’orientation et de l’insertion professionnelle
- Psychologues, psychothérapeutes
- Aides médico-psychologiques
- Spécialistes de l'appareillage médical
- Techniciens médicaux et préparateurs
- Infirmiers et sages-femmes
- Aides-soignants
- Professionnels de l'action sociale
- Professionnels de l'animation socioculturelle
- Sportifs et animateurs sportifs
- Surveillants d'établissements scolaires et accompagnateurs des élèves en situation de handicap
- Educateurs spécialisés et autres intervenants socio-éducatifs
- Autres professionnels para-médicaux
- Formateurs

=== Ouvriers de la construction et du bâtiment ===
- Ouvriers en montage réseaux électriques et télécoms
- Plombiers chauffagistes
- Ouvriers en pose et décoration de revêtements
- Ouvriers en peinture en bâtiment
- Ouvriers peu qualifiés en menuiserie et en agencement du BTP
- Ouvriers qualifiés en menuiserie et en agencement du BTP
- Conducteurs d'engins du bâtiment et des travaux publics
- Techniciens et agents de maîtrise de chantiers du BTP
- Professionnels du travail de la pierre et des matériaux associés
- Couvreurs
- Charpentiers (métal et bois)
- Maçons qualifiés
- Ouvriers en électricité du bâtiment
- Maçons peu qualifiés
- Ouvriers en travaux de façade, d'étanchéité et d'isolation
- Ouvriers peu qualifiés de l'extraction et des travaux publics
- Ouvriers qualifiés de l'extraction et des travaux publics
- Ouvriers de la construction en béton

=== Ouvriers des secteurs de l'industrie ===
- Ouvriers peu qualifiés en ajustement, montage et assemblage mécanique
- Tuyauteurs
- Ouvriers qualifiés en ajustement, montage et assemblage mécanique
- Ouvriers qualifiés de conduite d'installation de production de métaux
- Ouvriers peu qualifiés des industries chimiques et plastiques
- Ouviers peu qualifiés des industries agro-alimentaires
- Ouvriers qualifiés des industries chimiques et plastiques
- Techniciens en mécanique et travail des métaux
- Pilotes d'installation lourdes des industries de transformation et d'énergie
- Ouvriers peu qualifiés de conduite d'installation de production de métaux
- Ouvriers de l'industrie verrière, céramique et matériaux de construction
- Ouvriers en chaudronnerie et tôlerie
- Ouvriers de la peinture et du traitement de surface
- Ouvriers, techniciens et agents de maîtrise en traitement du cuir
- Ouvriers qualifiés du contrôle qualité et de laboratoire
- Ouvriers, techniciens et agents de maîtrise du textile
- Ouvriers, techniciens et agents de maîtrise de l'habillement
- Ouvriers de la réalisation d'ouvrages décoratifs et meubles en bois
- Ouvriers et techniciens de la scierie, de l'assemblage et de la fabrication d'ouvrages en bois
- Ouvriers, techniciens et agents de maîtrise de l'imprimerie
- Ouvriers de la maintenance générale et mécanique
- Ouvriers de la maintenance en électricité et en électronique
- Ouvriers polyvalents d'entretien du bâtiment
- Artisans et ouvriers de blanchisserie
- Techniciens des industries de process
- Artisans et ouvriers artisanaux
- Ouvriers mécaniciens de véhicules
- Ouvriers de l'électricité et de l'électronique
- Ouvriers peu qualifiés en conduite d'équipement d'usinage
- Ouvriers qualifiés en conduite d'équipement d'usinage
- Régleurs
- Ouvriers du conditionnement, du tri et de l'emballage
- Ouvriers en conduite d’équipement de fabrication de pâte à papier, de papier et de carton et de panneaux de bois
- Ouviers qualifiés des industries agro-alimentaires
- Mainteniciens en biens électrodomestiques
- Carrossiers automobiles
- Soudeurs

##

## Exploring job offers

In [105]:
df_region_filtered = df[df["Nom métier BMO"] == "Ingénieurs et cadres d'étude, recherche et développement en informatique et télécom"]
df_offers = df_region_filtered[['NOM_REG', 'met']]
df_groupby_region = df_offers.groupby('NOM_REG', as_index=False)['met'].sum()
df_region_sorted = df_groupby_region.sort_values(ascending=False, by="met")
df_region_sorted

                       NOM_REG    met
15               Île-de-France  11640
0         Auvergne-Rhône-Alpes   2019
12                   Occitanie   1869
14  Provence-Alpes-Côte d'Azur   1420
7              Hauts-de-France   1180
2                     Bretagne   1159
13            Pays de la Loire   1011
11          Nouvelle-Aquitaine    994
5                    Grand Est    600
10                   Normandie    270
3          Centre-Val de Loire    218
1      Bourgogne-Franche-Comté    101
8                   La Réunion     28
4                        Corse      0
6                   Guadeloupe      0
9                   Martinique      0